DarkPlasma_CustomKeyHandler:
  name: DarkPlasma_CustomKeyHandler
  year: 2021
  license: MIT
  histories:
    - date: '2021/10/10'
      version: '1.0.0'
      description: '初版'

  locates:
    - ja
  plugindesc:
    ja: 'ウィンドウのハンドラにカスタムキーを追加する'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      shiftなどを押した際のハンドラを追加できるようにします。

      (例) shiftキーハンドラをすべての選択可能ウィンドウに追加する:
      Window_CustomKeyHandlerMixIn("shift", Window_Selectable.prototype);
