DarkPlasma_SeverImmortality:
  name: DarkPlasma_SeverImmortality
  year: 2021
  license: MIT
  histories:
    - date: '2021/07/05'
      version: '1.0.2'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '1.0.1'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2021/04/16'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '倒した相手を復活不可にする行動'
  parameters: []
  commands: []
  structures:
  dependencies:
    base:
    orderAfter:
    orderBefore:
  help:
    ja: |
      下記のメモタグが設定されたスキルやアイテムで敵を倒すと、対象が復活不能になります。

      <severImmortality>

      復活とは、戦闘不能状態に陥った敵が下記いずれかの要因で戦闘に復帰することです。
      - HP回復スキルで回復する
      - 戦闘不能ステートを解除する行動でステートを解除する
      - イベントコマンド 敵キャラの全回復 で回復する
      - イベントコマンド 敵キャラのステート変更 で戦闘不能ステートを解除する
