DarkPlasma_SeverImmortality:
  name: DarkPlasma_SeverImmortality
  year: 2021
  license: MIT
  histories:
    - date: '2021/04/16'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '倒した相手を復活不可にする行動'
  parameters: []
  commands: []
  structures:
  dependencies:
    base:
    orderAfter:
    orderBefore:
  help:
    ja: |
      下記のメモタグが設定されたスキルやアイテムで敵を倒すと、対象が復活不能になります。

      <severImmortality>
