DarkPlasma_SurpriseControl:
  name: DarkPlasma_SurpriseControl
  year: 2020
  license: MIT
  histories:
    - date: '2021/06/22'
      version: '2.0.1'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/09/08'
      version: '2.0.0'
      description: 'パラメータ名を変更'
    - date: '2020/08/27'
      version: '1.0.1'
      description: 'イベントコマンドの戦闘の処理で無限に戦闘が繰り返される不具合を修正'
    - date: '2020/08/26'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '先制攻撃/不意打ちの制御を行う'
  parameters:
    - param: noPreemptiveSwitch
      text:
        ja: 先制攻撃しなくなるスイッチ番号
      desc:
        ja: 指定したスイッチがONのとき、プレイヤーサイドが先制攻撃しなくなります
      type: switch
      default: 0
    - param: noSurpriseSwitch
      text:
        ja: 先制攻撃されなくなるスイッチ番号
      desc:
        ja: 指定したスイッチがONのとき、エネミーサイドが先制攻撃しなくなります
      type: switch
      default: 0
    - param: forcePreemptiveSwitch
      text:
        ja: 必ず先制攻撃するスイッチ番号
      desc:
        ja: 指定したスイッチがONのとき、プレイヤーサイドが確実に先制攻撃します
      type: switch
      default: 0
    - param: forceSurpriseSwitch
      text:
        ja: 必ず先制攻撃されるスイッチ番号
      desc:
        ja: 指定したスイッチがONのとき、エネミーサイドが確実に先制攻撃します
      type: switch
      default: 0
    - param: enableWithEventCommand
      text:
        ja: 戦闘の処理でも有効
      desc:
        ja: イベントコマンド「戦闘の処理」でも先制判定を行うかどうか
      type: boolean
      default: true
  commands: []
  structures:
  help:
    ja: |
      プレイヤーサイド、エネミーサイドの先制攻撃を制御します。
      プラグインパラメータで特定スイッチがONのときに
      先制攻撃しない/されない/する/される設定ができます。

      複数のスイッチがONのとき、優先度は以下のようになります。

      必ず先制攻撃する > 必ず先制攻撃される > 先制攻撃しない/されない

      エネミーのメモ欄に<NoPreemptive>, <NoSurprise>,
      <ForcePreemptive>, <ForceSurprise>と記述をすることで、
      その敵が含まれる戦闘において、
      先制しない/されない/する/される設定ができます。

      <NoPreemptive>: プレイヤーサイドが先制攻撃しない
      <NoSurprise>: エネミーサイドが先制攻撃しない
      <ForcePreemptive>: プレイヤーサイドが必ず先制攻撃する
      <ForceSurprise>: エネミーサイドが必ず先制攻撃する

      上記が複数含まれるパターンの戦闘においては、優先度は以下のようになります。

      必ず先制攻撃する > 必ず先制攻撃される > 先制攻撃しない/されない
