DarkPlasma_DisableShowFastMessage:
  name: DarkPlasma_DisableShowFastMessage
  year: 2020
  license: MIT
  histories:
    - date: '2021/06/22'
      version: '1.0.2'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/10/10'
      version: '1.0.1'
      description: 'リファクタ'
    - date: '2020/09/26'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'メッセージの高速表示を禁止する'
  parameters: []
  commands:
    - command: Enable showFastMessage
      text:
        ja: メッセージ高速表示許可
      args: []
    - command: Disable showFastMessage
      text:
        ja: メッセージ高速表示禁止
      args: []
  structures:
  help:
    ja: |
      プラグインコマンドにより、メッセージの高速表示を禁止したり許可したりします。
