DarkPlasma_StateGroup:
  name: DarkPlasma_StateGroup
  year: 2020
  license: MIT
  histories:
    - date: '2021/07/05'
      version: '1.0.3'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '1.0.2'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/09/08'
      version: '1.0.1'
      description: 'rollup構成へ移行'
    - date: '2020/08/27'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: 'ステートをグルーピングして優先度付する'
  parameters: []
  commands: []
  structures:
  help:
    ja: |
      ステートをグルーピングして優先度付します。
      同じグループに属するステートは重ねがけできず、
      同じグループの優先度の高いステートで上書きされます。

      ステートのメモ欄に以下のように記述してください。

      <StateGroup:（グループ名）> グループ名は任意の文字列です。
      毒 や Poison など、グループに名前をつけてください。
      <StatePriority:x> xは数値です。数値が大きいほど優先度が高くなります。
