DarkPlasma_BattleItemVisibility:
  name: DarkPlasma_BattleItemVisibility
  year: 2020
  license: MIT
  histories:
    - date: '2021/07/05'
      version: '2.0.4'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '2.0.3'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/11/13'
      version: '2.0.2'
      description: '武器を表示する設定が効かない不具合を修正'
    - date: '2020/09/11'
      version: '2.0.1'
      description: '戦闘中にアイテム欄を開くとエラーが出る不具合を修正'
    - date: '2020/09/08'
      version: '2.0.0'
      description: 'パラメータ名を変更'
    - date: '2020/08/27'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '戦闘中のアイテムリストに表示するものを制御する'
  parameters:
    - param: showOnlyMenuItems
      text:
        ja: メニュー画面アイテムを表示
      desc:
        ja: メニュー画面のみ使用可能なアイテムを表示します
      type: boolean
      default: false
    - param: showUnusableItems
      text:
        ja: 使用不可アイテムを表示
      desc:
        ja: 使用不可アイテムを表示します
      type: boolean
      default: false
    - param: showWeapons
      text:
        ja: 武器を表示
      desc:
        ja: 武器を表示します
      type: boolean
      default: false
    - param: showArmors
      text:
        ja: 防具を表示
      desc:
        ja: 防具を表示します
      type: boolean
      default: false
    - param: showImportantItems
      text:
        ja: 大事なものを表示
      desc:
        ja: 大事なものを表示します
      type: boolean
      default: false
    - param: showUsableSecretItems
      text:
        ja: 使用可能隠しアイテムを表示
      desc:
        ja: 戦闘中に使用可能な隠しアイテムを表示します
      type: boolean
      default: false
    - param: showUnusableSecretItemsA
      text:
        ja: 使用不可隠しアイテムAを表示
      desc:
        ja: 戦闘中に使用不可能な隠しアイテムAを表示します
      type: boolean
      default: false
    - param: showUnusableSecretItemsB
      text:
        ja: 使用不可隠しアイテムBを表示
      desc:
        ja: 戦闘中に使用不可能な隠しアイテムBを表示します
      type: boolean
      default: false
  help:
    ja: |
      戦闘中のアイテムコマンドで表示されるアイテム一覧に表示するアイテムを設定します。
      プラグインパラメータで種別ごとに表示するものを設定できる他、
      アイテムのメモ欄に以下のように入力したアイテムを表示します。

      <VisibleInBattle>
