DarkPlasma_FreezePlayer:
  name: DarkPlasma_FreezePlayer
  year: 2022
  license: MIT
  histories:
    - date: 2022/04/10
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'プレイヤーの移動を禁止する'
  parameters:
    - param: switchId
      text:
        ja: スイッチ
      desc:
        ja: このスイッチがONの間、プレイヤーは移動できません。
      type: switch
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      スイッチがONの間、プレイヤーの移動を禁止します。
