DarkPlasma_AlwaysCritical:
  name: DarkPlasma_AlwaysCritical
  year: 2020
  license: MIT
  histories:
    - date: '2021/07/05'
      version: '1.0.2'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '1.0.1'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/09/10'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '常時クリティカルが出るスキル'
  parameters: []
  commands: []
  structures:
  help:
    ja: |
      スキルのメモ欄に<alwaysCritical>と書くと、
      そのスキルが常にクリティカルヒットします。
