DarkPlasma_AdjustEnemyPosition:
  name: DarkPlasma_AdjustEnemyPosition
  year: 2020
  license: MIT
  histories:
    - date: '2021/06/22'
      version: '1.0.1'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/11/13'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '敵の座標をUIエリアサイズに合わせて移動する'
  parameters: []
  commands: []
  structures:
  help:
    ja: |
      敵の配置をUIエリアサイズに合わせて移動します。

      MZ 1.3.0より、公式にこの機能が取り込まれました。
      本プラグインはそれより前のバージョンでのみ有効です。
