DarkPlasma_NPCKeepOutRegion:
  name: DarkPlasma_NPCKeepOutRegion
  year: 2021
  license: MIT
  histories:
    - date: '2021/11/09'
      version: '1.1.0'
      description: '移動制限無視をメモ欄で制御するように変更'
    - date: '2021/07/05'
      version: '1.0.2'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '1.0.1'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2021/04/20'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'イベントが通れないリージョンを指定する'
  parameters:
    - param: regions
      text:
        ja: リージョン一覧
      desc:
        ja: イベントが通行できないリージョン一覧を設定します。
      type: number[]
      default: []
  commands: []
  structures:
  dependencies:
    base:
    orderAfter:
    orderBefore:
  help:
    ja: |
      プラグインパラメータで指定したリージョンのマスについて、
      イベントが通行できなくなります。

      イベントのメモ欄に特定の記述をすることで、この通行制限を無視できます。

      <ignoreKeepOut>
      このメモタグが記述されたイベントは無条件で通行制限を無視する

      <ignoreKeepOut:A>
      このメモタグが記述されたイベントは、
      セルフスイッチAがONの場合に通行制限を無視する
