DarkPlasma_BountyList:
  name: DarkPlasma_BountyList
  version: '2.0.2'
  year: 2020
  license: MIT
  histories:
    - date: '2021/07/05'
      version: '2.0.4'
      description: 'MZ 1.3.2に対応'
    - date: '2021/06/22'
      version: '2.0.3'
      description: 'サブフォルダからの読み込みに対応'
    - date: '2020/10/10'
      version: '2.0.2'
      description: 'リファクタ'
    - date: '2020/09/29'
      version: '2.0.1'
      description: 'プラグインコマンドの説明を追加'
    - date: '2020/09/08'
      version: '2.0.0'
      description: 'パラメータ名変更'
    - date: '2020/08/24'
      version: '1.0.1'
      description: 'URL修正'
    - date: '2020/08/24'
      version: '1.0.0'
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '賞金首リストを表示する'
  parameters:
    - param: bountyInformations
      text:
        ja: 賞金首情報
      desc:
        ja: 賞金首リストに表示する情報。このリストの順番どおりに表示します
      type: BountyInformation[]
      default:
        - metaTag: 'bountyRequest'
          text: '依頼内容'
        - metaTag: 'bountyWhere'
          text: '出現場所'
        - metaTag: 'bountyReward'
          text: '討伐報酬'
        - metaTag: 'bountyDifficulty'
          text: '討伐難度'
        - metaTag: 'bountyDescription'
          text: ''
    - param: unknownName
      text:
        ja: 未表示名
      desc:
        ja: 表示条件を満たさないエネミーの表示名
      type: string
      default: ？？？？？？
    - param: showKilledBounty
      text:
        ja: 撃破後自動表示
      desc:
        ja: 撃破した賞金首を自動的に表示する
      type: boolean
      default: true
    - param: textOffsetX
      text:
        ja: テキストオフセットX
      desc:
        ja: 横方向のオフセット
      type: number
      default: 0
    - param: textOffsetY
      text:
        ja: テキストオフセットY
      desc:
        ja: 縦方向のオフセット
      type: number
      default: 0
    - param: textColorNormal
      text:
        ja: 倒してない敵の色
      desc:
        ja: リスト内の倒していない敵の文字色
      type: number
      default: 0
    - param: textColorKilled
      text:
        ja: 倒した敵の色
      desc:
        ja: リスト内の倒した敵の文字色
      type: number
      default: 7
  structures:
    BountyInformation:
      - param: metaTag
        desc:
          ja: メタタグ。<(指定した名前):hoge> をエネミーのメモ欄に記入する
        text:
          ja: メタタグ
        type: string
      - param: text
        desc:
          ja: 表示上のテキスト
        text:
          ja: テキスト
        type: string
  commands:
    - command: BountyList open
      text:
        ja: 賞金首シーンを開く
      desc:
        ja: 賞金首シーンを開きます。
      args: []
    - command: BountyList add
      text:
        ja: 敵キャラを賞金首リストに表示
      desc:
        ja: 指定した敵キャラを賞金首リスト内で開示します。
      args:
        - arg: id
          text:
            ja: 敵キャラID
          type: enemy
    - command: BountyList remove
      text:
        ja: 敵キャラを賞金首リストから非表示
      desc:
        ja: 指定した敵キャラを賞金首リストで非表示にします。
      args:
        - arg: id
          text:
            ja: 敵キャラID
          type: enemy
    - command: BountyList complete
      text:
        ja: 賞金首リストを全開示
      desc:
        ja: 賞金首リストを全開示します。
    - command: BountyList clear
      text:
        ja: 賞金首リストを初期化
      desc:
        ja: 賞金首リストを初期化します。
  help:
    ja: |
      賞金首に指定したいエネミーのメモ欄に以下の記述をしてください。

      <isBounty>
      <bountyShowSwitch:xx> スイッチxx番がONなら表示する

      賞金首リストには、<isBounty>が設定されており、
      なおかつ以下のいずれかを満たす敵キャラが表示されます。
      - 倒したことがある
      - <bountyShowSwitch:xx>を指定しており、スイッチxx番がONである

      また、表示したい情報があれば、
      賞金首情報を設定した上で、以下のように記述してください。

      <bountyRequest:賞金首の依頼内容>
      <bountyWhere:賞金首の出現場所>
      <bountyReward:賞金首の報酬>
      <bountyDifficulty:賞金首の討伐難度>
      <bountyDescription:賞金首の説明>

      これはデフォルトの設定例であり、
      賞金首情報の設定次第でお好みの要素を追加できます。

      賞金首リストをプログラムから開く:
      SceneManager.push(Scene_BountyList);
