DarkPlasma_TestBase:
  name: DarkPlasma_TestBase
  year: 2020
  license: MIT
  histories:
    - date: '2021/01/11'
      version: '2.4.0'
      description: 'テストケースプラグインの手動読み込みを許可する'
    - date: '2020/10/30'
      version: '2.3.0'
      description: 'mustBeTrueを追加'
    - date: '2020/10/26'
      version: '2.2.0'
      description: '0より大の整数値,要素を持つ配列のためのspecを作りやすくする機能追加'
    - date: '2020/10/24'
      version: '2.1.0'
      description: 'プラグインコマンド起因でテストする機能追加'
    - date: '2020/10/23'
      version: '2.0.0'
      description: 'Scene_BootのaddTestCaseを削除'
    - date: '2020/10/23'
      version: '2.0.0'
      description: 'テストケースウィンドウの表示が固定化される不具合を修正'
    - date: '2020/10/23'
      version: '1.0.1'
      description: '不要コードの削除'
    - date: '2020/10/22'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'プラグインの半自動テストをサポートする'
  parameters: []
  commands:
    - command: openTestCase
      text:
        ja: テストケースシーンを開く
      desc:
        ja: テストケースシーンを開きます。
    - command: doTest
      text:
        ja: テスト実行
      desc:
        ja: プラグインコマンド起因のテストを実行します。
  structures:
  help:
    ja: |
      本プラグインはプラグインの半自動テストをサポートします。

      Scene_Boot.prototype.defineTestCaseをフックしてテストケースを定義してください。
      以下のインターフェースで定義できます。
      this.addTestCase(string pluginName, string version, string testCaseName, boolean isAuto);

      テストの実行結果を登録するには以下のように書きます。
      $testTargetPlugins.doTest(string pluginName, string version, string testCaseName, TestSpec[] testSpecs);
